// flow-typed signature: e8ff644c635215f6411123be904e24e7
// flow-typed version: <<STUB>>/azur_v^0.0.6/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'azur'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'azur' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'azur/dist/application' {
  declare module.exports: any;
}

declare module 'azur/dist/index' {
  declare module.exports: any;
}

declare module 'azur/dist/lib/extract' {
  declare module.exports: any;
}

declare module 'azur/dist/lib/tmp' {
  declare module.exports: any;
}

declare module 'azur/src/application' {
  declare module.exports: any;
}

declare module 'azur/src/index' {
  declare module.exports: any;
}

declare module 'azur/src/lib/extract' {
  declare module.exports: any;
}

declare module 'azur/src/lib/tmp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'azur/dist/application.js' {
  declare module.exports: $Exports<'azur/dist/application'>;
}
declare module 'azur/dist/index.js' {
  declare module.exports: $Exports<'azur/dist/index'>;
}
declare module 'azur/dist/lib/extract.js' {
  declare module.exports: $Exports<'azur/dist/lib/extract'>;
}
declare module 'azur/dist/lib/tmp.js' {
  declare module.exports: $Exports<'azur/dist/lib/tmp'>;
}
declare module 'azur/src/application.js' {
  declare module.exports: $Exports<'azur/src/application'>;
}
declare module 'azur/src/index.js' {
  declare module.exports: $Exports<'azur/src/index'>;
}
declare module 'azur/src/lib/extract.js' {
  declare module.exports: $Exports<'azur/src/lib/extract'>;
}
declare module 'azur/src/lib/tmp.js' {
  declare module.exports: $Exports<'azur/src/lib/tmp'>;
}
