// flow-typed signature: ae3c24a967cfce628f9f2beee9ac1955
// flow-typed version: <<STUB>>/geojson2svg_v^1.2.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geojson2svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geojson2svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geojson2svg/dist/geojson2svg' {
  declare module.exports: any;
}

declare module 'geojson2svg/dist/geojson2svg.min' {
  declare module.exports: any;
}

declare module 'geojson2svg/examples/js/getjson' {
  declare module.exports: any;
}

declare module 'geojson2svg/examples/js/reproject.min' {
  declare module.exports: any;
}

declare module 'geojson2svg/examples/js/world-pop' {
  declare module.exports: any;
}

declare module 'geojson2svg/examples/js/world' {
  declare module.exports: any;
}

declare module 'geojson2svg/src/converter' {
  declare module.exports: any;
}

declare module 'geojson2svg/src/extend' {
  declare module.exports: any;
}

declare module 'geojson2svg/src/instance' {
  declare module.exports: any;
}

declare module 'geojson2svg/src/main' {
  declare module.exports: any;
}

declare module 'geojson2svg/test/test' {
  declare module.exports: any;
}

declare module 'geojson2svg/test/testdata' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geojson2svg/dist/geojson2svg.js' {
  declare module.exports: $Exports<'geojson2svg/dist/geojson2svg'>;
}
declare module 'geojson2svg/dist/geojson2svg.min.js' {
  declare module.exports: $Exports<'geojson2svg/dist/geojson2svg.min'>;
}
declare module 'geojson2svg/examples/js/getjson.js' {
  declare module.exports: $Exports<'geojson2svg/examples/js/getjson'>;
}
declare module 'geojson2svg/examples/js/reproject.min.js' {
  declare module.exports: $Exports<'geojson2svg/examples/js/reproject.min'>;
}
declare module 'geojson2svg/examples/js/world-pop.js' {
  declare module.exports: $Exports<'geojson2svg/examples/js/world-pop'>;
}
declare module 'geojson2svg/examples/js/world.js' {
  declare module.exports: $Exports<'geojson2svg/examples/js/world'>;
}
declare module 'geojson2svg/src/converter.js' {
  declare module.exports: $Exports<'geojson2svg/src/converter'>;
}
declare module 'geojson2svg/src/extend.js' {
  declare module.exports: $Exports<'geojson2svg/src/extend'>;
}
declare module 'geojson2svg/src/instance.js' {
  declare module.exports: $Exports<'geojson2svg/src/instance'>;
}
declare module 'geojson2svg/src/main.js' {
  declare module.exports: $Exports<'geojson2svg/src/main'>;
}
declare module 'geojson2svg/test/test.js' {
  declare module.exports: $Exports<'geojson2svg/test/test'>;
}
declare module 'geojson2svg/test/testdata.js' {
  declare module.exports: $Exports<'geojson2svg/test/testdata'>;
}
