// flow-typed signature: d8dd2f7d1ae6887a40ef602fb694e1b7
// flow-typed version: <<STUB>>/httpolyglot_v^0.1.2/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'httpolyglot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'httpolyglot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'httpolyglot/lib/index' {
  declare module.exports: any;
}

declare module 'httpolyglot/test/common' {
  declare module.exports: any;
}

declare module 'httpolyglot/test/test-early-disconnect' {
  declare module.exports: any;
}

declare module 'httpolyglot/test/test-normal' {
  declare module.exports: any;
}

declare module 'httpolyglot/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'httpolyglot/lib/index.js' {
  declare module.exports: $Exports<'httpolyglot/lib/index'>;
}
declare module 'httpolyglot/test/common.js' {
  declare module.exports: $Exports<'httpolyglot/test/common'>;
}
declare module 'httpolyglot/test/test-early-disconnect.js' {
  declare module.exports: $Exports<'httpolyglot/test/test-early-disconnect'>;
}
declare module 'httpolyglot/test/test-normal.js' {
  declare module.exports: $Exports<'httpolyglot/test/test-normal'>;
}
declare module 'httpolyglot/test/test.js' {
  declare module.exports: $Exports<'httpolyglot/test/test'>;
}
