// flow-typed signature: bb143fc06da9dc2e34a8c81c0188d8db
// flow-typed version: <<STUB>>/node-hook_v^1.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-hook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-hook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'node-hook/index' {
  declare module.exports: $Exports<'node-hook'>;
}
declare module 'node-hook/index.js' {
  declare module.exports: $Exports<'node-hook'>;
}
