// flow-typed signature: fc355c9ec06034cb7a1236b16a31eaee
// flow-typed version: <<STUB>>/selfsigned_v^1.10.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'selfsigned'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'selfsigned' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'selfsigned/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'selfsigned/index' {
  declare module.exports: $Exports<'selfsigned'>;
}
declare module 'selfsigned/index.js' {
  declare module.exports: $Exports<'selfsigned'>;
}
declare module 'selfsigned/test/tests.js' {
  declare module.exports: $Exports<'selfsigned/test/tests'>;
}
