// flow-typed signature: 2be2f5039fdc1913f9aa2c43d0c3832d
// flow-typed version: <<STUB>>/@babel/preset-flow_v7.0.0-beta.44/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/preset-flow/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/preset-flow/lib/index.js' {
  declare module.exports: $Exports<'@babel/preset-flow/lib/index'>;
}
